aws_region                = "ca-central-1"
stack                     = "terraform-fastapi"
fargate-task-service-role = "terraform-fatsapi-role"
aws_ecr                   = "fastapi"
aws_profile               = "vscode"
source_repo_name          = "Yas2020"
source_repo_branch        = "main"
image_repo_name           = "fastapi"

codestar_connector_credentials = "arn:aws:codestar-connections:*******:connection/*******"

database_hostname = "db"
database_password = "Password123"
database_name     = "fastapi"
database_port     = "5432"
database_username = "postgres"
secret_key        = "SomeString-anything!"
algorithm         = "HS256"
minutes           = "30"